
vscode:
  extensions:
    - eventyret.bootstrap-4-cdn-snippet
    - formulahendry.auto-close-tag
    - ms-toolsai.jupyter
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
    - ms-python.python
